export const INIT_SOCKET = 'INIT_SOCKET'
export const SOCKET_CLOSED = 'SOCKET_CLOSED'

export const SCRAPE = 'SCRAPE'
export const SCRAPER_COMPLETE = 'SCRAPER_COMPLETE'
export const SCRAPER_ERROR = 'SCRAPER_ERROR'
export const SCRAPER_RESET = 'SCRAPER_RESET'

export const DOWNLOAD_CSV_REQ = 'DOWNLOAD_CSV_REQ'
export const DOWNLOAD_CSV_COMPLETE = 'DOWNLOAD_CSV_COMPLETE'
export const DOWNLOAD_JSON_REQ = 'DOWNLOAD_JSON_REQ'
export const DOWNLOAD_JSON_COMPLETE = 'DOWNLOAD_JSON_COMPLETE'
