sudo: false
language: node_js
node_js:
  - "6"
  - "7"
  - "node"

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - npm run deploy:dev
  - npm run deploy:prod

after_success:
  - npm run codecov
