sudo: false
language: node_js
node_js:
  - "6"

services:
  - docker

cache:
  directories:
    - node_modules

install:
  - npm install -g yarn
  - yarn install

script:
  - npm run deploy:dev
  - npm run deploy:prod

after_success:
  - npm run codecov
  - if [ "$TRAVIS_BRANCH" == "production" ]; then
    echo "Login as user $DOCKER_USERNAME"
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker build -t philbot/youtube-comment-scraper2.0 .;
    docker images;
    docker push philbot/youtube-comment-scraper2.0;
    fi
