export const INIT_SOCKET = 'INIT_SOCKET'
export const SOCKET_CLOSED = 'SOCKET_CLOSED'

export const SCRAPE = 'SCRAPE'
export const SCRAPER_COMPLETE = 'SCRAPER_COMPLETE'
export const SCRAPER_ERROR = 'SCRAPER_ERROR'
export const SCRAPER_RESET = 'SCRAPER_RESET'
export const COMMENT_RECEIVED = 'COMMENT_RECEIVED'
