export const TOGGLE_COLUMN = 'TOGGLE_COLUMN'
export const TOGGLE_MULTIPLE_COLUMNS = 'TOGGLE_MULTIPLE_COLUMNS'
export const SET_INCLUDE_REPLIES = 'SET_INCLUDE_REPLIES'
export const SET_REPLIES_COLLAPSED = 'SET_REPLIES_COLLAPSED'
