export const TOGGLE_COLUMN = 'TOGGLE_COLUMN'
export const TOGGLE_MULTIPLE_COLUMNS = 'TOGGLE_MULTIPLE_COLUMNS'
export const TOGGLE_REPLIES = 'TOGGLE_REPLIES'
export const TOGGLE_COLLAPSED_REPLIES = 'TOGGLE_COLLAPSED_REPLIES'
